repo: "using-markbot"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    search:
      - "Hello World!"
